/**
 * Story 7.7 — RTL coverage for AIIntelligenceStrip (closes TEST-001 from 7.2 QA).
 *
 * Critical paths:
 * - Empty state (no sessions)
 * - Non-overridden row renders ✦ AI indicator
 * - Coach-overridden row renders Coach edited chip + Regenerate button
 * - Regenerate button calls PATCH with clear_overrides
 * - Pro tier shows enabled Refresh; Free tier shows disabled
 */

import { render, screen, waitFor, fireEvent } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { AIIntelligenceStrip } from '../AIIntelligenceStrip';
import type { AIIntelligenceStrip as Strip } from '@meetsolis/shared';

jest.mock('sonner', () => ({
  toast: { success: jest.fn(), error: jest.fn() },
}));

const BASE_STRIP: Strip = {
  recurring_theme: 'imposter syndrome',
  theme_frequency: '3 of 5 sessions',
  recent_breakthrough: 'named the inner critic',
  current_focus: 'pacing big decisions',
  generated_at: '2026-06-09T00:00:00.000Z',
};

function renderStrip(
  props: Partial<React.ComponentProps<typeof AIIntelligenceStrip>>
) {
  const qc = new QueryClient({
    defaultOptions: { queries: { retry: false } },
  });
  return render(
    <QueryClientProvider client={qc}>
      <AIIntelligenceStrip
        clientId="11111111-1111-1111-1111-111111111111"
        strip={BASE_STRIP}
        coachNotes=""
        hasSessions
        {...props}
      />
    </QueryClientProvider>
  );
}

function mockFetch(tier: 'pro' | 'free' = 'pro') {
  global.fetch = jest.fn((url: string, init?: RequestInit) => {
    if (url === '/api/usage') {
      return Promise.resolve({
        ok: true,
        json: async () => ({ tier }),
      } as Response);
    }
    if (init?.method === 'PATCH') {
      return Promise.resolve({
        ok: true,
        json: async () => ({ strip: BASE_STRIP }),
      } as Response);
    }
    return Promise.resolve({
      ok: true,
      json: async () => ({ strip: BASE_STRIP }),
    } as Response);
  }) as unknown as typeof fetch;
}

describe('AIIntelligenceStrip', () => {
  beforeEach(() => {
    jest.clearAllMocks();
    mockFetch('pro');
  });

  it('renders empty state when no sessions', () => {
    renderStrip({ strip: null, hasSessions: false });
    expect(
      screen.getByText(/building your intelligence profile/i)
    ).toBeInTheDocument();
  });

  it('renders the three editable rows when strip present', () => {
    renderStrip({});
    expect(screen.getByText(/recurring theme/i)).toBeInTheDocument();
    expect(screen.getByText(/recent breakthrough/i)).toBeInTheDocument();
    expect(screen.getByText(/current focus/i)).toBeInTheDocument();
  });

  it('shows ✦ AI indicator on non-overridden rows', () => {
    renderStrip({});
    // Each AI indicator chip exposes title="Generated by AI"
    const aiChips = screen.getAllByTitle('Generated by AI');
    // 3 narrative fields, each with an AIIndicator since no overrides
    expect(aiChips.length).toBe(3);
  });

  it('shows Coach edited chip + Regenerate button on overridden rows', () => {
    renderStrip({
      overrides: { recurring_theme: true },
    });
    expect(screen.getByText(/coach edited/i)).toBeInTheDocument();
    expect(
      screen.getByRole('button', { name: /regenerate/i })
    ).toBeInTheDocument();
    // Other two rows still show ✦ AI
    expect(screen.getAllByTitle('Generated by AI').length).toBe(2);
  });

  it('Regenerate button PATCHes with clear_overrides for that field', async () => {
    renderStrip({
      overrides: { current_focus: true },
    });
    const regenBtn = screen.getByRole('button', { name: /regenerate/i });
    fireEvent.click(regenBtn);

    await waitFor(() => {
      const patchCall = (global.fetch as jest.Mock).mock.calls.find(
        c => c[1]?.method === 'PATCH'
      );
      expect(patchCall).toBeDefined();
      expect(patchCall[1].body).toContain('clear_overrides');
      expect(patchCall[1].body).toContain('current_focus');
    });
  });

  it('Pro tier shows enabled Refresh button', async () => {
    renderStrip({});
    await waitFor(() => {
      const refresh = screen.getByRole('button', { name: /refresh insights/i });
      expect(refresh).not.toBeDisabled();
    });
  });

  it('Free tier shows disabled Refresh button with upgrade tooltip', async () => {
    mockFetch('free');
    renderStrip({});
    await waitFor(() => {
      const refresh = screen.getByRole('button', { name: /refresh insights/i });
      expect(refresh).toBeDisabled();
      expect(refresh).toHaveAttribute(
        'title',
        expect.stringMatching(/upgrade to pro/i)
      );
    });
  });
});
