export interface ServiceStatus {
  status: 'healthy' | 'degraded' | 'unavailable';
  responseTime: number;
  lastCheck: Date;
  errorCount: number;
}

export interface ServiceInfo {
  name: string;
  version: string;
  description: string;
  dependencies: string[];
}

export interface ExternalService {
  isAvailable(): Promise<boolean>;
  fallbackMode(): boolean;
  healthCheck(): Promise<ServiceStatus>;
  getServiceInfo(): ServiceInfo;
  getCircuitBreakerState(): string;
}

export interface AuthService extends ExternalService {
  authenticate(credentials: any): Promise<any>;
  logout(): Promise<void>;
  getCurrentUser(): Promise<any>;
}

export interface DatabaseService extends ExternalService {
  query(sql: string, params?: any[]): Promise<any>;
  insert(table: string, data: any): Promise<any>;
  update(table: string, id: string, data: any): Promise<any>;
  delete(table: string, id: string): Promise<any>;
}

export interface ClientContext {
  name: string;
  goal?: string | null;
  coaching_since?: string | null;
}

// Summary + action items are generated by separate AI calls (Story 6.2c).
export interface SessionSummaryResult {
  // Optional — a concise AI-generated session title. Applied only when the
  // session has no real title yet (Story 6.2c follow-up).
  title?: string;
  summary: string;
  key_topics: string[];
}

export interface ActionItemResult {
  description: string;
  // 'unknown' (Story 7.6) — ambiguous attribution ("we should...").
  assigned_to: 'coach' | 'client' | 'unknown';
}

export interface ActionItemsResult {
  action_items: ActionItemResult[];
}

// Story 7.2 — AI intelligence strip input + output (omit generated_at; wrapper adds it).
export interface IntelligenceStripInput {
  client: {
    name: string;
    goal: string | null;
    start_date: string | null;
  };
  // Most-recent-first. Most recent 3 are passed verbatim; older are condensed by caller.
  sessions: Array<{
    session_date: string;
    summary: string;
    key_topics: string[];
  }>;
}

export interface IntelligenceStripFields {
  recurring_theme: string;
  theme_frequency: string;
  recent_breakthrough: string;
  current_focus: string;
}

// Story 7.7 — AI session-tag classification input/output. Closed-set tags.
export interface ClassifySessionTagsInput {
  summary: string;
  key_topics: string[];
}

export interface ClassifySessionTagsResult {
  // 1-2 of: 'breakthrough', 'stuck', 'milestone', 'goal-setting'.
  // Validated against SESSION_TAGS by caller — service returns raw model output.
  tags: string[];
}

export interface AIService extends ExternalService {
  generateSummary(text: string): Promise<string>;
  analyzeText(text: string): Promise<any>;
  summarizeSession(
    transcript: string,
    ctx: ClientContext
  ): Promise<SessionSummaryResult>;
  generateActionItems(
    transcript: string,
    ctx: ClientContext
  ): Promise<ActionItemsResult>;
  generateEmbedding(text: string): Promise<number[]>;
  querySolis(systemPrompt: string, userPrompt: string): Promise<string>;
  /**
   * Story 6.4 — narrative AI Prep Note generation for Coach Brief.
   * Higher-temperature, creative output (NOT JSON). Returns plain text.
   */
  generatePrepNote(systemPrompt: string, userPrompt: string): Promise<string>;
  /**
   * Story 7.2 — AI intelligence strip for Client Card. JSON output, 4 fields.
   * Wrapper (generate-intelligence-strip.ts) adds generated_at + writes to DB.
   */
  generateIntelligenceStrip(
    input: IntelligenceStripInput
  ): Promise<IntelligenceStripFields>;
  /**
   * Story 7.7 — classify a session into 1–2 of 4 tags.
   * Returns raw tags array; caller validates against SESSION_TAGS enum.
   */
  classifySessionTags(
    input: ClassifySessionTagsInput
  ): Promise<ClassifySessionTagsResult>;
}

export interface TranscriptionResult {
  text: string;
  duration_seconds?: number;
  confidence?: number;
}

export interface TranscriptionService extends ExternalService {
  transcribe(audioUrl: string): Promise<TranscriptionResult>;
}

export interface TranslationService extends ExternalService {
  translate(text: string, targetLanguage: string): Promise<string>;
  detectLanguage(text: string): Promise<string>;
}

export interface SMSService extends ExternalService {
  sendSMS(to: string, message: string): Promise<boolean>;
}

export interface AnalyticsService extends ExternalService {
  track(event: string, properties?: any): Promise<void>;
  identify(userId: string, traits?: any): Promise<void>;
}

export interface ErrorTrackingService extends ExternalService {
  captureException(error: Error): Promise<void>;
  captureMessage(message: string, level?: string): Promise<void>;
}

export interface CalendarService extends ExternalService {
  createEvent(event: any): Promise<any>;
  updateEvent(eventId: string, event: any): Promise<any>;
  deleteEvent(eventId: string): Promise<void>;
  getEvents(start: Date, end: Date): Promise<any[]>;
}