/**
 * Stream SDK Client Initialization
 *
 * This module provides both server-side and client-side initialization
 * for Stream Video SDK. The server client is used for token generation
 * and administrative tasks, while the client-side client is used for
 * joining video calls.
 */

import { StreamClient } from '@stream-io/node-sdk';
import { StreamVideoClient } from '@stream-io/video-react-sdk';

/**
 * Get Stream server client for backend operations
 * Used for:
 * - Generating user tokens
 * - Creating/managing users
 * - Administrative operations
 *
 * @returns StreamClient instance
 * @throws Error if API keys are not configured
 */
export const getStreamServerClient = (): StreamClient => {
  const apiKey = process.env.STREAM_API_KEY;
  const apiSecret = process.env.STREAM_API_SECRET;

  if (!apiKey || !apiSecret) {
    throw new Error(
      'Stream API credentials not configured. Please set STREAM_API_KEY and STREAM_API_SECRET in .env.local'
    );
  }

  return new StreamClient(apiKey, apiSecret);
};

/**
 * Create Stream video client for frontend video calls
 * This should be called on the client-side after obtaining a token
 * from the backend.
 *
 * @param userId - Clerk user ID
 * @param userName - User's display name
 * @param token - JWT token generated by server
 * @returns StreamVideoClient instance
 * @throws Error if API key is not configured
 */
export const createStreamVideoClient = (
  userId: string,
  userName: string,
  token: string
): StreamVideoClient => {
  const apiKey = process.env.NEXT_PUBLIC_STREAM_API_KEY;

  if (!apiKey) {
    throw new Error(
      'Stream API key not configured. Please set NEXT_PUBLIC_STREAM_API_KEY in .env.local'
    );
  }

  return new StreamVideoClient({
    apiKey,
    user: {
      id: userId,
      name: userName,
    },
    token,
  });
};

/**
 * Generate a Stream user token on the server
 *
 * @param userId - Clerk user ID
 * @param validityInSeconds - Token validity duration (default: 1 hour)
 * @returns JWT token string
 */
export const generateStreamUserToken = (
  userId: string,
  validityInSeconds: number = 3600
): string => {
  const client = getStreamServerClient();

  return client.generateUserToken({
    user_id: userId,
    validity_in_seconds: validityInSeconds,
  });
};

/**
 * Create or update a Stream user
 * This should be called when a user joins a meeting for the first time
 *
 * @param userId - Clerk user ID
 * @param userName - User's display name
 * @param role - User role (default: 'user')
 */
export const upsertStreamUser = async (
  userId: string,
  userName: string,
  role: string = 'user'
): Promise<void> => {
  const client = getStreamServerClient();

  await client.upsertUsers({
    users: {
      [userId]: {
        id: userId,
        name: userName,
        role,
      },
    },
  });
};
