/**
 * Story 7.7 — "✦ AI" indicator chip.
 *
 * Rendered next to AI-generated fields so coaches understand the field came
 * from automation. Drops when a coach overrides the field (replaced by a
 * "Coach edited" chip in the parent component).
 */

import { Sparkles } from 'lucide-react';

export function AIIndicator() {
  return (
    <span
      title="Generated by AI"
      className="inline-flex items-center gap-0.5 rounded-full border border-primary/15 bg-primary/[0.05] px-1.5 py-0.5 text-[9px] font-medium text-primary/70 normal-case tracking-normal"
    >
      <Sparkles className="h-2.5 w-2.5" />
      AI
    </span>
  );
}
